# Build Workflow
name: build

# Run on Push
on: [push]

jobs:
  build:
    # Run this on a default linux machine
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Create build directory
        run: |
          mkdir -p build
          cp index.html build/

      - name: Build DFS
        run: |
          cd dfs
          ../docker.sh
          cp -r build ../build/dfs

      - name: Build watercolor
        run: |
          cd watercolor
          ../docker.sh
          cp -r build ../build/watercolor

      - name: Build interference
        run: |
          cd interference
          ../docker.sh
          cp -r build ../build/interference

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build